name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: jotavmk
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Criar o diretório dist/ caso não exista
      - name: Create dist directory
        run: |
          mkdir -p dist

      # Copiar README.md para o diretório dist/
      - name: Copy README to dist
        run: cp README.md dist/README.md

      # Usar a ação para enviar os arquivos para o GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
